In [2]:
import pandas as pd
import numpy  as np


In [3]:
dict = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df = pd.DataFrame.from_dict(dict)
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [4]:
#or
df2 = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
print(df2)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [5]:
#2
data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

In [6]:
labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(data,index =labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [7]:
#3
df = pd.DataFrame(data,index=labels)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


In [8]:
#4
print(df.iloc[:3])

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [9]:
#5
print(df[['name','score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [10]:
temp_df = df[['score','qualify']]
print(temp_df.iloc[[1,3,5,6]]) #6

   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


In [11]:
#7
boolean_mask = df['attempts'] > 2
print(df[boolean_mask])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [12]:
df.shape #8


(10, 4)

In [13]:
#9
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)

print(df[df['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [14]:
#10

print(df[df['score'].between(15,20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [15]:
print(df.query("score > 15 and attempts < 2"))

    name  score  attempts qualify
j  Jonas   19.0         1     yes


In [16]:
df.loc['d','score'] = 11.5
print(df)


        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [17]:
# df.drop(columns='d', inplace=True)

In [18]:
#13

print(df['attempts'].sum())

19


In [19]:
#14
df.loc['d','score'] = np.nan
print(df['score'].mean())

13.5625


In [20]:
#x1
states = ['Alabama','Alaska','Arizona','Arkansas',
          'California','Colorado','Connecticut','Delaware',
          'Florida','Georgia','Hawaii','Idaho',
          'Illinois','Indiana','Iowa','Kansas']
pops = {
"California": 39237836,
"Texas": 29527941,
"Florida": 21781128,
"New York": 19835913,
"Pennsylvania": 12964056,
"Illinois": 12671469,
"Ohio": 11780017,
"Georgia": 10799566
}

In [21]:
print(len(states))
#16

16


In [22]:
print(states[3][2:])

kansas


In [23]:
print(states[2:13:3])
#Arizona, Colorado,Florida,Idaho

['Arizona', 'Colorado', 'Florida', 'Idaho']


In [24]:
# print(pops[ states[-7] ]) #4 
# print("New York" in pops) #5
# for state in states:
#     if state in pops:
#         print(state) #6

In [25]:
# 2. Write the following codes using pandas:
# (a) Create a DateFrame df
# +-------+------+------+------+------+------+---+
# | | AZ | PT | VW | KK | PQ | C |
# +-------+------+------+------+------+------+---+
# | r5303 | 0.58 | 0.33 | 0.05 | 0.34 | 0.04 | 1 |
# | r6578 | 0.68 | 0.59 | 0.73 | 0.87 | 0.32 | 1 |
# | r7750 | 0.75 | 0.74 | 0.56 | 0.06 | 0.86 | 1 |
# | r5481 | 0.55 | 0.47 | 0.85 | 0.12 | 0.03 | 0 |
# +-------+------+------+------+------+------+---+
# (b) Print the number of rows of df
# (c) Count the number of rows with each label of column C
# (d) Select and order top 2 entries of column PT
# (e) Select a subset of df as follows:
# +-------+------+------+------+
# | | PT | VW | KK |
# +-------+------+------+------+
# | r5303 | 0.33 | 0.05 | 0.34 |
# | r7750 | 0.74 | 0.56 | 0.06 |
# +-------+------+------+------+
# (f) Print the maximum value in each column except the last column C
df = pd.DataFrame(
    {
        "AZ" : [.58,.68,.75,.55],
        "PT" : [.33,.59,.74,.47],
        "VW" : [.05,.73,.56,.85],
        "KK" : [.34,.87,.06,.12],
        "PQ" : [.04,.32,.86,.03],
        "C" : [1,1,1,0]
    },
    index = ["r5303","r6578","r7750","r5481"]

)
print(df)

         AZ    PT    VW    KK    PQ  C
r5303  0.58  0.33  0.05  0.34  0.04  1
r6578  0.68  0.59  0.73  0.87  0.32  1
r7750  0.75  0.74  0.56  0.06  0.86  1
r5481  0.55  0.47  0.85  0.12  0.03  0


In [26]:
print(len(df)) #(b) 

4


In [27]:
print(df['C'].value_counts()) #(c)

C
1    3
0    1
Name: count, dtype: int64


In [31]:
# print(df.nlargest(2,'PT')) #(d)
# print(df.sort_values('PT', ascending=False)[0:2])

         AZ    PT    VW    KK    PQ  C
r7750  0.75  0.74  0.56  0.06  0.86  1
r6578  0.68  0.59  0.73  0.87  0.32  1


In [36]:
#(e)
print(df.loc[['r5303','r7750'], ['PT','VW','KK']])


         PT    VW    KK
r5303  0.33  0.05  0.34
r7750  0.74  0.56  0.06


In [53]:
#(f)
print(df.drop(columns="C").max())

AZ    0.75
PT    0.74
VW    0.85
KK    0.87
PQ    0.86
dtype: float64


In [54]:
# #Numpy Section

# 3. Write the following codes in NumPy:
# (a) Create three row arrays (Do not type individual elements explicitly)
# a = [ -3, -1, 1, 3, 5, 7, 9 ]
# b = [ 1, 2.2, 3.4, 4.6, 5.8, 7, 8.2 ]
# c = [ 5, 5, 5, 5, 5, 5, 5, 5 ]
# (b) Calculate the dot product of a and b
# (c) Use the three vectors to create a 3 x 4 matrix d , such that the first, second, and third rows consist
# of the last four elements of the vectors a , b , and c , respectively
# (d) Show the number of elements of d (output should be 12)
# (e) Reshape matrix d to a 4 x 3 matrix e
# (f) Create a 3 element array f with numbers that are the greatest elements of each columns of e

In [63]:
a = np.arange(-3,10,2)
print(a)
b = np.arange(1, 8.3, 1.2)
print(b)
c= np.full(8,5)
print(c)

[-3 -1  1  3  5  7  9]
[1.  2.2 3.4 4.6 5.8 7.  8.2]
[5 5 5 5 5 5 5 5]


In [65]:
print(np.dot(a,b))

163.8
