In [1]:
import pandas as pd
import numpy as np

In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(f"a {a}")
b = np.zeros([2,3,4])
print(f"b {b}")
c = np.ones([2,3,4])
print(f"c {c}")
d = np.arange(7,12,2)
print(f"d {d} ")
e = np.linspace(0,2,9, endpoint=True)
print(f"e {e}")

a [[1 2 3]
 [4 5 6]]
b [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
c [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
d [ 7  9 11] 
e [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [14]:
# linspace, give me inbetween numbers in inclusive #,#, and # numbers. example: 0 to 2, give me 9 numbers

In [35]:
e2 = np.linspace(0,2,9,endpoint=False)
print(e2)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778]


In [34]:
f = np.full((2,3,4),7)
print(f)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


In [33]:
#random
r = np.random.random((2,3))
print(r)

[[0.55482452 0.76032857 0.300481  ]
 [0.51877799 0.79424813 0.51115086]]


In [37]:
t = np.random.randint(1,7,[5,5])
print(t)

[[4 1 4 6 2]
 [3 4 2 2 5]
 [1 3 4 2 2]
 [1 6 5 4 1]
 [5 4 3 3 3]]


In [ ]:
#matrix multiplication on first test    

In [38]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[2,3],[3,4]])
c = a @ b
print(c)

[[14 20]
 [32 47]]


In [39]:
a = np.array([[1,2,3],[4,5,6]])
#i want to know if a > 3.
a > 3

array([[False, False, False],
       [ True,  True,  True]])

In [42]:
a = np.random.random([2,3,4])
print(a)
print("-----------------")
print(a.max(axis=1))

[[[0.91863909 0.09167878 0.40813161 0.92929082]
  [0.86110706 0.48254751 0.096356   0.54495282]
  [0.20508987 0.71495092 0.95921392 0.71231251]]

 [[0.32709217 0.23034843 0.19938243 0.46934886]
  [0.63386989 0.31015066 0.80419202 0.36228893]
  [0.82102399 0.63341251 0.92788686 0.23153384]]]
-----------------
[[0.91863909 0.71495092 0.95921392 0.92929082]
 [0.82102399 0.63341251 0.92788686 0.46934886]]


In [ ]:
#numpy problems on x1